# Generated by Django 5.0.6 on 2024-06-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0003_rename_cargo_colaborador_id_cargo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("Ativo", "Ativo"),
                    ("Afastado", "Afastado"),
                    ("Demitido", "Demitido"),
                ],
                default="Ativo",
                max_length=100,
            ),
        ),
    ]
