# Generated by Django 5.0.6 on 2024-06-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0004_alter_colaborador_situacao"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cargo",
            table="cargos",
        ),
        migrations.AlterModelTable(
            name="colaborador",
            table="colaboradores",
        ),
        migrations.AlterModelTable(
            name="departamento",
            table="departamentos",
        ),
    ]
