# Generated by Django 5.0.6 on 2024-06-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0005_alter_cargo_table_alter_colaborador_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="colaborador",
            options={"ordering": ["nome"]},
        ),
    ]
