# Generated by Django 5.0.6 on 2024-06-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0007_alter_cargo_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departamento",
            name="descricao",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
