# Generated by Django 5.0.6 on 2024-11-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0009_colaborador_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="cpf",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
