# Generated by Django 5.0.6 on 2024-11-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0010_alter_colaborador_cpf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="colaborador",
            old_name="id_cargo",
            new_name="cargo",
        ),
        migrations.RenameField(
            model_name="colaborador",
            old_name="id_departamento",
            new_name="departamento",
        ),
    ]
