# Generated by Django 5.0.6 on 2024-06-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="especialidadefornecedor",
            name="descricao",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
