# Generated by Django 5.0.6 on 2024-08-23 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colaboradores", "0008_alter_departamento_descricao"),
        ("frota", "0008_manutencaogeral_centro_custo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SituacaoMulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "situacao_multas",
            },
        ),
        migrations.CreateModel(
            name="Multa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_infracao", models.DateField()),
                ("hora_infracao", models.TimeField()),
                ("auto_infracao", models.CharField(max_length=255)),
                (
                    "gravidade",
                    models.CharField(
                        choices=[
                            ("Leve", "Leve"),
                            ("Média", "Média"),
                            ("Grave", "Grave"),
                            ("Gravíssima", "Gravíssima"),
                        ],
                        max_length=100,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_vencimento", models.DateField()),
                ("data_pagamento", models.DateField(null=True)),
                ("descricao", models.TextField()),
                (
                    "centro_custo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frota.centrocusto",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="colaboradores.colaborador",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frota.veiculo",
                    ),
                ),
                (
                    "situacao_multa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="seguranca.situacaomulta",
                    ),
                ),
            ],
            options={
                "db_table": "multas",
            },
        ),
    ]
