# Generated by Django 5.0.6 on 2024-08-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguranca", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multa",
            name="auto_infracao",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
