# Generated by Django 5.0.6 on 2024-08-28 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguranca", "0002_alter_multa_auto_infracao"),
    ]

    operations = [
        migrations.CreateModel(
            name="SituacaoPagamentoMulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "situacao_pagamento_multas",
            },
        ),
        migrations.RemoveField(
            model_name="multa",
            name="data_pagamento",
        ),
        migrations.AddField(
            model_name="multa",
            name="situacao_pagamento",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="seguranca.situacaopagamentomulta",
            ),
        ),
    ]
