# Generated by Django 5.0.6 on 2024-08-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "seguranca",
            "0003_situacaopagamentomulta_remove_multa_data_pagamento_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="multa",
            name="situacao_pagamento",
        ),
    ]
