# Generated by Django 5.0.6 on 2024-08-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seguranca", "0004_remove_multa_situacao_pagamento"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SituacaoPagamentoMulta",
        ),
    ]
