# Generated by Django 5.0.6 on 2024-08-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguranca", "0005_delete_situacaopagamentomulta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multa",
            name="situacao_multa",
            field=models.CharField(
                choices=[
                    ("A Pagar", "A Pagar"),
                    ("Pago", "Pago"),
                    ("Recorrendo", "Recorrendo"),
                    ("Anulada", "Anulada"),
                ],
                default="A pagar",
                max_length=100,
            ),
        ),
        migrations.DeleteModel(
            name="SituacaoMulta",
        ),
    ]
