# Generated by Django 5.0.6 on 2024-09-12 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0008_alter_departamento_descricao"),
        ("frota", "0008_manutencaogeral_centro_custo"),
        ("seguranca", "0006_alter_multa_situacao_multa_delete_situacaomulta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multa",
            name="situacao_multa",
            field=models.CharField(
                choices=[
                    ("A Pagar", "A Pagar"),
                    ("Pago", "Pago"),
                    ("Recorrendo", "Recorrendo"),
                    ("Anulada", "Anulada"),
                ],
                default="A Pagar",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Ocorrido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_ocorrido", models.DateField()),
                (
                    "tipo_ocorrido",
                    models.CharField(
                        choices=[
                            ("Acidente", "Acidente"),
                            ("Incidente", "Incidente"),
                            ("Perda ou Furto", "Perda ou Furto"),
                        ],
                        max_length=100,
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("Não Solucionado", "Não Solucionado"),
                            ("Solucionado", "Solucionado"),
                        ],
                        default="Não Solucionado",
                        max_length=100,
                    ),
                ),
                (
                    "prejudicado_nome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prejudicado_cpf",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "documento_prejudicado",
                    models.FileField(
                        blank=True, null=True, upload_to="ocorridos/documentos/"
                    ),
                ),
                (
                    "comprovante_pagamento",
                    models.FileField(
                        blank=True, null=True, upload_to="ocorridos/comprovantes/"
                    ),
                ),
                (
                    "foto1",
                    models.ImageField(
                        blank=True, null=True, upload_to="ocorridos/fotos_ocorrido/"
                    ),
                ),
                (
                    "foto2",
                    models.ImageField(
                        blank=True, null=True, upload_to="ocorridos/fotos_ocorrido/"
                    ),
                ),
                (
                    "foto3",
                    models.ImageField(
                        blank=True, null=True, upload_to="ocorridos/fotos_ocorrido/"
                    ),
                ),
                (
                    "foto4",
                    models.ImageField(
                        blank=True, null=True, upload_to="ocorridos/fotos_ocorrido/"
                    ),
                ),
                (
                    "foto5",
                    models.ImageField(
                        blank=True, null=True, upload_to="ocorridos/fotos_ocorrido/"
                    ),
                ),
                (
                    "video_ocorrido",
                    models.FileField(
                        blank=True, null=True, upload_to="ocorridos/videos_ocorrido"
                    ),
                ),
                (
                    "centro_custo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frota.centrocusto",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="colaboradores.colaborador",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frota.veiculo",
                    ),
                ),
            ],
            options={
                "db_table": "ocorridos",
            },
        ),
    ]
