# Generated by Django 5.0.6 on 2024-09-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seguranca", "0007_alter_multa_situacao_multa_ocorrido"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ocorrido",
            old_name="prejudicado_cpf",
            new_name="prejudicado_cpf_cnpj",
        ),
    ]
