# Generated by Django 5.0.6 on 2024-09-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguranca", "0008_rename_prejudicado_cpf_ocorrido_prejudicado_cpf_cnpj"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrido",
            name="data_finalizacao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ocorrido",
            name="ordem_pagamento",
            field=models.FileField(
                blank=True, null=True, upload_to="ocorridos/comprovantes/"
            ),
        ),
    ]
