# Generated by Django 5.0.6 on 2024-09-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguranca", "0009_ocorrido_data_finalizacao_ocorrido_ordem_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrido",
            name="valor",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
