# Generated by Django 5.0.6 on 2024-11-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguranca", "0011_remove_ocorrido_data_finalizacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocorrido",
            name="responsabiliza_condutor",
            field=models.CharField(
                choices=[(1, "Sim"), (2, "Não")], default=1, max_length=100
            ),
            preserve_default=False,
        ),
    ]
