# Generated by Django 5.0.6 on 2024-11-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguranca", "0012_alter_ocorrido_responsabiliza_condutor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocorrido",
            name="responsabiliza_condutor",
            field=models.CharField(
                choices=[("Sim", "Sim"), ("Não", "Não")], max_length=100
            ),
        ),
    ]
