# Generated by Django 5.0.6 on 2024-12-18 16:43

import seguranca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguranca", "0013_alter_ocorrido_responsabiliza_condutor"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrido",
            name="orcamento",
            field=models.FileField(
                blank=True, null=True, upload_to=seguranca.models.caminho_orcamento
            ),
        ),
    ]
