# Generated by Django 5.0.6 on 2025-05-07 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguranca", "0014_ocorrido_orcamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="multa",
            name="data_cadastro",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
