# Generated by Django 5.0.6 on 2024-06-14 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Combustivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "combustiveis",
            },
        ),
        migrations.CreateModel(
            name="GrupoVeiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "grupos_veiculos",
            },
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=7, unique=True)),
                (
                    "porte",
                    models.CharField(
                        choices=[
                            ("Pequeno", "Pequeno"),
                            ("Médio", "Médio"),
                            ("Grande", "Grande"),
                        ],
                        max_length=100,
                    ),
                ),
                ("modelo", models.CharField(max_length=100)),
                ("marca", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("renavam", models.CharField(max_length=100)),
                ("chassi", models.CharField(max_length=100)),
                (
                    "situacao",
                    models.CharField(
                        choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                        default="Ativo",
                        max_length=100,
                    ),
                ),
                (
                    "combustivel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frota.combustivel",
                    ),
                ),
                (
                    "grupo_veiculo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frota.grupoveiculo",
                    ),
                ),
            ],
            options={
                "db_table": "veiculos",
            },
        ),
    ]
