# Generated by Django 5.0.6 on 2024-06-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0008_alter_departamento_descricao"),
        ("fornecedores", "0002_alter_especialidadefornecedor_descricao"),
        ("frota", "0002_maquina"),
    ]

    operations = [
        migrations.CreateModel(
            name="Causa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "causas_manutencoes",
            },
        ),
        migrations.CreateModel(
            name="CentroCusto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "centros_custos",
            },
        ),
        migrations.CreateModel(
            name="Tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "tipos_manutencoes",
            },
        ),
        migrations.CreateModel(
            name="ManutencaoVeiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("documento", models.CharField(max_length=255)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_inicial", models.DateField()),
                ("hora_inicial", models.TimeField()),
                ("data_final", models.DateField()),
                ("hora_final", models.TimeField()),
                ("descricao", models.TextField()),
                (
                    "causa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frota.causa",
                    ),
                ),
                (
                    "centro_custo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frota.centrocusto",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="colaboradores.colaborador",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fornecedores.fornecedor",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frota.veiculo",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frota.tipo",
                    ),
                ),
            ],
            options={
                "db_table": "manutencoes_veiculos",
            },
        ),
    ]
