# Generated by Django 5.0.6 on 2024-06-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frota", "0003_causa_centrocusto_tipo_manutencaoveiculo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manutencaoveiculo",
            name="data_final",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="manutencaoveiculo",
            name="data_inicial",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="manutencaoveiculo",
            name="hora_final",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="manutencaoveiculo",
            name="hora_inicial",
            field=models.TimeField(null=True),
        ),
    ]
