# Generated by Django 5.0.6 on 2024-06-26 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0008_alter_departamento_descricao"),
        ("fornecedores", "0002_alter_especialidadefornecedor_descricao"),
        ("frota", "0004_alter_manutencaoveiculo_data_final_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManutencaoMaquina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("documento", models.CharField(max_length=255)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_inicial", models.DateField(null=True)),
                ("hora_inicial", models.TimeField(null=True)),
                ("data_final", models.DateField(null=True)),
                ("hora_final", models.TimeField(null=True)),
                ("descricao", models.TextField()),
                (
                    "causa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frota.causa",
                    ),
                ),
                (
                    "centro_custo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frota.centrocusto",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="colaboradores.colaborador",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fornecedores.fornecedor",
                    ),
                ),
                (
                    "maquina",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frota.maquina",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frota.tipo",
                    ),
                ),
            ],
            options={
                "db_table": "manutencoes_maquinas",
            },
        ),
    ]
