# Generated by Django 5.0.6 on 2024-06-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frota", "0005_manutencaomaquina"),
    ]

    operations = [
        migrations.AddField(
            model_name="maquina",
            name="situacao",
            field=models.CharField(
                choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                default="Ativo",
                max_length=100,
            ),
        ),
    ]
