# Generated by Django 5.0.6 on 2024-06-26 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedores", "0002_alter_especialidadefornecedor_descricao"),
        ("frota", "0006_maquina_situacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManutencaoGeral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("documento", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("Veículos", "Veículos"), ("Máquinas", "Máquinas")],
                        max_length=100,
                    ),
                ),
                (
                    "causa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frota.causa",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fornecedores.fornecedor",
                    ),
                ),
            ],
            options={
                "db_table": "manutencoes_gerais",
            },
        ),
    ]
