# Generated by Django 5.0.6 on 2024-06-27 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frota", "0007_manutencaogeral"),
    ]

    operations = [
        migrations.AddField(
            model_name="manutencaogeral",
            name="centro_custo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="frota.centrocusto",
            ),
        ),
    ]
