# Generated by Django 5.0.6 on 2024-11-07 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0008_alter_departamento_descricao"),
        ("frota", "0008_manutencaogeral_centro_custo"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoCombustivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "tipos_combustivel",
            },
        ),
        migrations.CreateModel(
            name="Abastecimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateField()),
                ("litros", models.DecimalField(decimal_places=2, max_digits=10)),
                ("hodometro_transacao", models.PositiveIntegerField()),
                ("hodometro_anterior", models.PositiveIntegerField()),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="colaboradores.colaborador",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frota.veiculo",
                    ),
                ),
                (
                    "tipo_combustivel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frota.tipocombustivel",
                    ),
                ),
            ],
            options={
                "db_table": "abastecimentos",
            },
        ),
    ]
