# Generated by Django 5.0.6 on 2024-11-07 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frota", "0009_tipocombustivel_abastecimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abastecimento",
            name="tipo_combustivel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="frota.combustivel",
            ),
        ),
        migrations.DeleteModel(
            name="TipoCombustivel",
        ),
    ]
