# Generated by Django 5.0.6 on 2024-11-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frota", "0010_alter_abastecimento_tipo_combustivel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abastecimento",
            name="data_hora",
            field=models.DateTimeField(),
        ),
    ]
