# Generated by Django 5.0.6 on 2024-11-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frota", "0011_alter_abastecimento_data_hora"),
    ]

    operations = [
        migrations.AddField(
            model_name="abastecimento",
            name="valor_transacao",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
