# Generated by Django 5.0.6 on 2024-11-09 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frota", "0012_abastecimento_valor_transacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="abastecimento",
            name="centro_custo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="frota.centrocusto",
            ),
        ),
    ]
