# Generated by Django 5.0.6 on 2024-12-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frota", "0013_abastecimento_centro_custo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manutencaoveiculo",
            name="data_final",
        ),
        migrations.RemoveField(
            model_name="manutencaoveiculo",
            name="data_inicial",
        ),
        migrations.RemoveField(
            model_name="manutencaoveiculo",
            name="hora_final",
        ),
        migrations.RemoveField(
            model_name="manutencaoveiculo",
            name="hora_inicial",
        ),
    ]
