# Generated by Django 5.0.6 on 2024-12-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frota", "0014_remove_manutencaoveiculo_data_final_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manutencaomaquina",
            name="data_final",
        ),
        migrations.RemoveField(
            model_name="manutencaomaquina",
            name="data_inicial",
        ),
        migrations.RemoveField(
            model_name="manutencaomaquina",
            name="hora_final",
        ),
        migrations.RemoveField(
            model_name="manutencaomaquina",
            name="hora_inicial",
        ),
    ]
