# Generated by Django 5.0.6 on 2024-12-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frota", "0015_remove_manutencaomaquina_data_final_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abastecimento",
            name="data_hora",
        ),
        migrations.AddField(
            model_name="abastecimento",
            name="data",
            field=models.DateField(blank=True, null=True),
        ),
    ]
