# Generated by Django 5.0.6 on 2024-12-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frota", "0016_remove_abastecimento_data_hora_abastecimento_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abastecimento",
            name="data",
            field=models.DateField(),
        ),
    ]
