# Generated by Django 5.0.6 on 2025-03-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frota", "0017_alter_abastecimento_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manutencaogeral",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Veículos", "Veículos"),
                    ("Máquinas", "Máquinas"),
                    ("Paleteira", "Paleteira"),
                ],
                max_length=100,
            ),
        ),
    ]
